{% set name = "mgltools" %}
{% set version = "1.5.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: http://{{ name }}.scripps.edu/downloads/downloads/tars/releases/REL{{ version }}/{{ name }}_x86_64Linux2_{{ version }}.tar.gz  # [linux]
    sha256: d4f1493a175cd67cf2f54e6f585c430e1093d3bbd33817b82345dc2a58676a0f  # [linux]
  # OSX builds fail for some weird reason as of Aug 2020. Will skip the build for OSX.
  - url: http://{{ name }}.scripps.edu/downloads/downloads/tars/releases/REL{{ version }}/{{ name }}_i86Darwin9_{{ version }}.tar.gz  # [osx]
    sha256: 15f9f64015270bfa6fa3091c7278e442a77e73d5db6d20ffe45ae019294a3d17  # [osx]

build:
  number: 4
  skip: True  # [not linux]

test:
  commands:
    - pmv --help
    - prepare_ligand4.py
    - prepare_receptor4.py
    - pythonsh --help
    - test ! -z $AUTODOCKTOOLS_UTIL  # [not win]
    - test $AUTODOCKTOOLS_UTIL == ${CONDA_PREFIX}/MGLToolsPckgs/AutoDockTools/Utilities24  # [not win]

about:
  home: http://mgltools.scripps.edu
  license: custom
  license_file: LICENSES
  summary: MGLTools is an program for visualization and analysis of molecular structures
